package com.sysensor.config.table;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.sysensor.config.config.TableNameConfig;


@DynamoDBTable(tableName = TableNameConfig.ApplicationConfig)
public class ApplicationConfig {

    public static final String ID = "id";
    public static final String NAME = "name";
    public static final String REGION = "region";

    private String id;
    private String name;
    private String region;


    public ApplicationConfig() {
    }

    public ApplicationConfig(String name, String region) {
        this.name = name;
        this.region = region;
    }

    @DynamoDBHashKey(attributeName = ID)
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBRangeKey(attributeName = NAME)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute(attributeName = REGION)
    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    @Override
    public String toString() {
        return "ApplicationConfig{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", region='" + region + '\'' +
                '}';
    }
}
